/*
PURPOSE:    Simulate the power generated by a solar array by following the IV curve
*/

#ifndef SOLAR_POWER_SYSTEM_HH
#define SOLAR_POWER_SYSTEM_HH

#ifdef __cplusplus
	extern "C"
	{
#endif

class solar_array {
	public:
    	// Description: Default constructor for initializing a solar array object
    	solar_array();
    	
    	// Description: Constructor to initialize solar array with specified parameters
    	solar_array(double /*oc_voltage*/, double /*sc_current*/, double /*max_voltage*/, double /*max_current*/, double /*voltage_terminal*/);
    	
    	// Description: Initializes the solar array with given parameters
    	void initialize(double /*oc_voltage*/, double /*sc_current*/, double /*max_voltage*/, double /*max_current*/, double /*voltage_terminal*/);
    	
    	// Description: Updates the output current based on the current state
    	void update_I();
    	
    	// Description: Updates the terminal voltage of the solar array
    	void update_V(double /*voltage*/);
    	
    	// Description: Retrieves the output current of the solar array
    	double get_I();

		void set_I_sc(double);
    	
    	// Description: Retrieves an alternative output current for additional analysis
    	double get_I2();

	private:
    	// Equivalent Circuit Variables
    	// Algorithms can be run to optimize the solar array performance
    	
    	// Public variables
    	double V; /* Voltage of bus attached to the wire */
    	double V_test; /* Test voltage for calculations */
    	double I; /* Output current from the solar array */
    	double I2; /* Alternative output current for additional measurements */

    	double t; /* Time (in seconds) for I/O operations */
   	 
    	double I_sc; /* Short-circuit current */
    	double I_sc_max; /* Maximum short-circuit current */
    	double I_o; /* Reverse saturation current */
    	double V_oc; /* Open-circuit voltage */
    	double V_mp; /* Voltage at maximum power point */
    	double I_mp; /* Current at maximum power point */
    	double Rs; /* Series resistance */
    	double Rsh; /* Shunt resistance */
    	double Vt; /* Thermal voltage */
    	double n; /* Diode ideality factor */

    	double Tc_V; /* Temperature coefficient for voltage */
    	double Tc_I; /* Temperature coefficient for current */

    	double dI; /* Change in current per change in voltage */
};

#ifdef __cplusplus
	}
#endif

#endif
